# -*- coding: utf-8 -*-
"""sub.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zbz7f1U5qW3qRg9u_boBMz8jwsg6ffVS
"""

def subtract(n1,n2):
    print(n1-n2)
    
    #edited version
